version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssafy_web_db
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
