services:
  springboot:
    image: openjdk:17
    container_name: springboot_app
    build:
      context: ./springboot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./springboot:/app
    command: ["java", "-jar", "/app/target/app.jar"]

  nextjs:
    image: node:18
    container_name: nextjs_app
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

  fastapi:
    image: python:3.10
    container_name: fastapi_app
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
