build:
  date: "@build.date@"

server:
  port: 8080
  address: localhost
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: application/json, application/xml, text/html, text/xml, text/plain, application/javascript, text/css

# Import .env file
spring:
  config:
    import: optional:file:.env[.properties]

  # Database 설정
  datasource:
    url: jdbc:mysql://localhost:3306/ssafy_web_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: four4two

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    web:
      pageable:
        one-indexed-parameters: true

  devtools:
    livereload:
      enabled: true

# JWT 설정
jwt:
  secret: dyAeHubOOc8KaOfYB6XEQoEj1QzRlVgtjNL8PYs1A1tymZvvqkcEU7L1imkKHeDa
  expiration: 1296000000 # 15 days in milliseconds

# OAuth2 설정
spring.security:
  oauth2:
    client:
      registration:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          scope: email, profile

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    enabled: true

# 로깅 설정
logging:
  file:
    name: ./ssafy-web.log
  level:
    root: INFO
    com.samsung.security: DEBUG
    org.springframework.web: DEBUG
    org.apache.tiles: INFO
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG

# Health check (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true
