export const tarotCards: { [key: string]: string } = {
  // Major Arcana (maj0 ~ maj21)
  "maj0": "The Fool",
  "maj1": "The Magician",
  "maj2": "The High Priestess",
  "maj3": "The Empress",
  "maj4": "The Emperor",
  "maj5": "The Hierophant",
  "maj6": "The Lovers",
  "maj7": "The Chariot",
  "maj8": "Strength",
  "maj9": "The Hermit",
  "maj10": "Wheel of Fortune",
  "maj11": "Justice",
  "maj12": "The Hanged Man",
  "maj13": "Death",
  "maj14": "Temperance",
  "maj15": "The Devil",
  "maj16": "The Tower",
  "maj17": "The Star",
  "maj18": "The Moon",
  "maj19": "The Sun",
  "maj20": "Judgement",
  "maj21": "The World",

  // Cups
  "cups1": "Ace of Cups",
  "cups2": "Two of Cups",
  "cups3": "Three of Cups",
  "cups4": "Four of Cups",
  "cups5": "Five of Cups",
  "cups6": "Six of Cups",
  "cups7": "Seven of Cups",
  "cups8": "Eight of Cups",
  "cups9": "Nine of Cups",
  "cups10": "Ten of Cups",
  "cups11": "Page of Cups",
  "cups12": "Knight of Cups",
  "cups13": "Queen of Cups",
  "cups14": "King of Cups",

  // Pentacles
  "pents1": "Ace of Pentacles",
  "pents2": "Two of Pentacles",
  "pents3": "Three of Pentacles",
  "pents4": "Four of Pentacles",
  "pents5": "Five of Pentacles",
  "pents6": "Six of Pentacles",
  "pents7": "Seven of Pentacles",
  "pents8": "Eight of Pentacles",
  "pents9": "Nine of Pentacles",
  "pents10": "Ten of Pentacles",
  "pents11": "Page of Pentacles",
  "pents12": "Knight of Pentacles",
  "pents13": "Queen of Pentacles",
  "pents14": "King of Pentacles",

  // Wands
  "wands1": "Ace of Wands",
  "wands2": "Two of Wands",
  "wands3": "Three of Wands",
  "wands4": "Four of Wands",
  "wands5": "Five of Wands",
  "wands6": "Six of Wands",
  "wands7": "Seven of Wands",
  "wands8": "Eight of Wands",
  "wands9": "Nine of Wands",
  "wands10": "Ten of Wands",
  "wands11": "Page of Wands",
  "wands12": "Knight of Wands",
  "wands13": "Queen of Wands",
  "wands14": "King of Wands",

  // Swords
  "swords1": "Ace of Swords",
  "swords2": "Two of Swords",
  "swords3": "Three of Swords",
  "swords4": "Four of Swords",
  "swords5": "Five of Swords",
  "swords6": "Six of Swords",
  "swords7": "Seven of Swords",
  "swords8": "Eight of Swords",
  "swords9": "Nine of Swords",
  "swords10": "Ten of Swords",
  "swords11": "Page of Swords",
  "swords12": "Knight of Swords",
  "swords13": "Queen of Swords",
  "swords14": "King of Swords"
};

export const tarotCardsKorean: { [key: string]: string } = {
  // 메이저 아르카나 (maj0 ~ maj21)
  "maj0": "광대",
  "maj1": "마법사",
  "maj2": "여사제",
  "maj3": "여왕",
  "maj4": "황제",
  "maj5": "교황",
  "maj6": "연인",
  "maj7": "전차",
  "maj8": "힘",
  "maj9": "은둔자",
  "maj10": "운명의 수레바퀴",
  "maj11": "정의",
  "maj12": "매달린 사람",
  "maj13": "죽음",
  "maj14": "절제",
  "maj15": "악마",
  "maj16": "탑",
  "maj17": "별",
  "maj18": "달",
  "maj19": "태양",
  "maj20": "심판",
  "maj21": "세계",

  // 컵 (Cups)
  "cups1": "성배 1",
  "cups2": "성배 2",
  "cups3": "성배 3",
  "cups4": "성배 4",
  "cups5": "성배 5",
  "cups6": "성배 6",
  "cups7": "성배 7",
  "cups8": "성배 8",
  "cups9": "성배 9",
  "cups10": "성배 10",
  "cups11": "성배 시종",
  "cups12": "성배 기사",
  "cups13": "성배 여왕",
  "cups14": "성배 왕",

  // 펜타클 (Pentacles)
  "pents1": "동전 1",
  "pents2": "동전 2",
  "pents3": "동전 3",
  "pents4": "동전 4",
  "pents5": "동전 5",
  "pents6": "동전 6",
  "pents7": "동전 7",
  "pents8": "동전 8",
  "pents9": "동전 9",
  "pents10": "동전 10",
  "pents11": "동전 시종",
  "pents12": "동전 기사",
  "pents13": "동전 여왕",
  "pents14": "동전 왕",

  // 완드 (Wands)
  "wands1": "막대기 1",
  "wands2": "막대기 2",
  "wands3": "막대기 3",
  "wands4": "막대기 4",
  "wands5": "막대기 5",
  "wands6": "막대기 6",
  "wands7": "막대기 7",
  "wands8": "막대기 8",
  "wands9": "막대기 9",
  "wands10": "막대기 10",
  "wands11": "막대기 시종",
  "wands12": "막대기 기사",
  "wands13": "막대기 여왕",
  "wands14": "막대기 왕",

  // 소드 (Swords)
  "swords1": "검 1",
  "swords2": "검 2",
  "swords3": "검 3",
  "swords4": "검 4",
  "swords5": "검 5",
  "swords6": "검 6",
  "swords7": "검 7",
  "swords8": "검 8",
  "swords9": "검 9",
  "swords10": "검 10",
  "swords11": "검 시종",
  "swords12": "검 기사",
  "swords13": "검 여왕",
  "swords14": "검 왕"
};
